Repository prgrms-web-devcourse/Team_KPPL_STUTI_FE, pull requests merged in 2022-08, with the labels that each got.

#26 Feature / 스터디-카드-컴포넌트
  .storybook/preview.js
  src/components/StudyCard/MoreButton.style.ts
  src/components/StudyCard/MoreButton.tsx
  src/components/StudyCard/StudyCard.stories.js
  src/components/StudyCard/StudyCard.style.ts
  src/components/StudyCard/StudyCard.tsx
  src/components/index.ts
Labels: 리뷰 요청, 컴포넌트, 기능 구현

#32 Feature/스터디 상세페이지 UI 컴포넌트, 컨테이너, 페이지 구현
  public/mock/studyDetailMockData.json
  public/mock/studyDetailQustionMockData.json
  src/apis/axiosInstance.ts
  src/apis/studyDetail.ts
  src/assets/noImage.jpeg
  src/components/StudyDetail/DetailBody/DetailBody.stories.js
  src/components/StudyDetail/DetailBody/DetailBody.tsx
  src/components/StudyDetail/DetailBody/style.ts
  src/components/StudyDetail/DetailHeader/DetailHeader.stories.js
  src/components/StudyDetail/DetailHeader/DetailHeader.tsx
  src/components/StudyDetail/DetailHeader/style.ts
  src/components/StudyDetail/DetailLeaderInfo/DetailLeaderInfo.stories.js
  src/components/StudyDetail/DetailLeaderInfo/DetailLeaderInfo.tsx
  src/components/StudyDetail/DetailLeaderInfo/style.ts
  src/components/index.ts
  src/containers/Reply/Reply.tsx
  src/containers/Reply/ReplyInput.tsx
  src/containers/Reply/style.ts
  src/containers/StudyDetail/MbtiRecommand/MbtiRecommend.tsx
  src/containers/StudyDetail/MbtiRecommand/style.ts
  src/containers/StudyDetail/StudyInfo/StudyInfo.tsx
  src/containers/StudyDetail/StudyInfo/style.ts
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/containers/StudyDetail/StudyQuestion/style.ts
  src/containers/index.ts
  src/interfaces/assets.d.ts
  src/interfaces/studyDetail.d.ts
  src/interfaces/studyDetailQuestion.d.ts
  src/pages/Home/index.tsx
  src/pages/StudyDetail/index.tsx
  src/pages/StudyDetail/style.ts
  src/router/index.tsx
  tsconfig.json
Labels: 리뷰 요청, 프론트, 컴포넌트, 컨테이너, 페이지

#35 Feature/스터디-수정-페이지-컨테이너-UI
  src/apis/fetchStudyDetails.ts
  src/components/StudyCreate&Edit/StudyFileInput.stories.js
  src/components/StudyCreate&Edit/StudyFileInput.tsx
  src/components/StudyCreate&Edit/StudyLabelInput.stories.js
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate&Edit/StudyMultiLineInput.stories.js
  src/components/StudyCreate&Edit/StudyMultiLineInput.tsx
  src/components/StudyCreate&Edit/index.ts
  src/containers/StudyEdit/StudyEditForm.stories.js
  src/containers/StudyEdit/StudyEditForm.tsx
  src/containers/StudyEdit/style.ts
  src/containers/index.ts
  src/pages/StudyEdit/index.tsx
  src/router/index.tsx
Labels: 리뷰 요청, 컨테이너

#37 Feature/스터디 관리 페이지 UI 구현
  public/mock/studyManageMockData.json
  src/apis/studyManage.ts
  src/components/Mui/MuiInput.stories.js
  src/components/StudyDetail/DetailBody/style.ts
  src/components/StudyDetail/DetailHeader/DetailHeader.tsx
  src/components/StudyDetail/DetailHeader/style.ts
  src/components/StudyDetail/DetailLeaderInfo/DetailLeaderInfo.tsx
  src/components/StudyDetail/DetailLeaderInfo/style.ts
  src/components/UserInfo/UserInfo.stories.js
  src/components/UserInfo/UserInfo.tsx
  src/components/UserInfo/style.ts
  src/components/index.ts
  src/containers/Counter/style.ts
  src/containers/Reply/Reply.stories.js
  src/containers/Reply/Reply.tsx
  src/containers/Reply/style.ts
  src/containers/StudyDetail/MbtiRecommand/style.ts
  src/containers/StudyDetail/StudyInfo/style.ts
  src/containers/StudyDetail/StudyQuestion/style.ts
  src/containers/StudyManage/MemberControl/MemberControl.stories.js
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/containers/StudyManage/MemberControl/style.ts
  src/containers/index.ts
  src/interfaces/studyManage.d.ts
  src/pages/StudyDetail/index.tsx
  src/pages/StudyDetail/style.ts
  src/pages/StudyManage/index.tsx
  src/pages/StudyManage/style.ts
  src/router/index.tsx
Labels: 리뷰 요청, 프론트, 컨테이너, 페이지

#40 Feature/댓글-컨테이너-수정
  public/mock/studyDetailQustionMockData.json
  src/containers/Reply/Reply.stories.js
  src/containers/Reply/Reply.tsx
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/interfaces/studyDetailQuestion.d.ts
Labels: 리뷰 요청, 컨테이너, 리팩터링, 수정

#41 Feature/회원가입-페이지-UI-구현
  src/containers/SignUp/Form/Form.tsx
  src/containers/SignUp/Form/style.ts
  src/containers/SignUp/Select/Select.tsx
  src/containers/SignUp/options.ts
  src/containers/index.ts
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.ts
  src/router/index.tsx
Labels: 리뷰 요청, 컨테이너, 페이지, 기능 구현

#42 Feature/스터디-생성-수정-validation
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate&Edit/StudyMultiLineInput.tsx
  src/containers/StudyEdit/StudyEditForm.tsx
  src/containers/StudyEdit/style.ts
Labels: 리뷰 요청, 컨테이너, 기능 구현

#43 Feature/홈 프로필상세 페이지
  public/mock/studyList0.json
  public/mock/studyList1.json
  public/mock/studyList2.json
  public/mock/userProfile.json
  src/apis/members.ts
  src/apis/studyGroups.ts
  src/components/Button/Button.tsx
  src/components/Button/style.ts
  src/components/ProfileDetail/UserProfile/UserProfile.style.ts
  src/components/ProfileDetail/UserProfile/UserProfile.tsx
  src/components/SpinnerIcon/SpinnerIcon.tsx
  src/components/StudyCard/MoreButton/MoreButton.style.ts
  src/components/StudyCard/MoreButton/MoreButton.tsx
  src/components/StudyCard/StudyCard.stories.js
  src/components/StudyCard/StudyCard.style.ts
  src/components/StudyCard/StudyCard.tsx
  src/components/StudyList/StudyList.style.ts
  src/components/StudyList/StudyList.tsx
  src/components/index.ts
  src/constants/selectOptions.ts
  src/containers/Counter/Counter.tsx
  src/containers/Counter/style.ts
  src/containers/Home/HeroSection/HeroSection.style.ts
  src/containers/Home/HeroSection/HeroSection.tsx
  src/containers/Home/Select/Select.tsx
  src/containers/Home/StudyCreateButton/StudyCreateButton.style.ts
  src/containers/Home/StudyCreateButton/StudyCreateButton.tsx
  src/containers/Home/StudyListFilter/StudyListFilter.style.ts
  src/containers/Home/StudyListFilter/StudyListFilter.tsx
  src/containers/Home/StudyListSection/StudyListSection.style.ts
  src/containers/Home/StudyListSection/StudyListSection.tsx
  src/containers/ProfileDetail/ContentSection/ContentSection.style.ts
  src/containers/ProfileDetail/ContentSection/ContentSection.tsx
  src/containers/ProfileDetail/InfoSection/InfoSection.style.ts
  src/containers/ProfileDetail/InfoSection/InfoSection.tsx
  src/containers/ProfileDetail/PostTab/PostTab.tsx
  src/containers/ProfileDetail/StudyTab/StudyTab.tsx
  src/containers/index.ts
  src/hooks/useIntersectionObserver.ts
  src/interfaces/studyList.d.ts
  src/interfaces/userProfile.d.ts
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/index.tsx
  src/pages/ProfileDetail/ProfileDetail.tsx
  src/pages/ProfileEdit/ProfileEdit.tsx
  src/pages/index.ts
  src/router/index.tsx
  src/router/path.ts
  src/utils/getOptionLabel.ts
  tsconfig.paths.json
Labels: 페이지

#46 Feature/댓글 컨테이너 리펙토링
  public/mock/studyDetailQustionMockData.json
  src/components/DefaultAvatar/DefaultAvatar.stories.js
  src/components/DefaultAvatar/DefaultAvatar.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/index.ts
  src/containers/Reply/Reply.tsx
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/interfaces/studyDetailQuestion.d.ts
  src/styles/MuiProvider.jsx
  tsconfig.paths.json
Labels: 리뷰 요청, 프론트, 컨테이너, 리팩터링, 수정

#47 Feature/스터디 상세 UI 수정
  public/mock/studyDetailMockData.json
  public/mock/studyDetailQustionMockData.json
  src/containers/StudyDetail/StudyInfo/StudyInfo.tsx
  src/interfaces/studyDetail.d.ts
  src/pages/StudyDetail/index.tsx
  src/pages/StudyDetail/style.ts
  src/pages/StudyManage/index.tsx
  src/router/history.ts
  src/router/index.tsx
  src/router/routeHelper.ts
Labels: 리뷰 요청, 프론트, 페이지, 기능 구현, 리팩터링, 수정

#50 Feature/헤더-컨테이너-UI-수정
  src/components/LogoIcon/LogoIcon.tsx
  src/containers/NavigationHeader/NavigationHeader.tsx
  src/containers/NavigationHeader/style.ts
Labels: 리뷰 요청, 컨테이너, 리팩터링, 수정

#52 Feature/커뮤니티 페이지
  public/mock/CommunityMockData.json
  src/apis/community.ts
  src/components/FeedModal/FeedModal.stories.js
  src/components/FeedModal/FeedModal.style.ts
  src/components/FeedModal/FeedModal.tsx
  src/components/FeedModal/FeedModalImageUpload/FeedModalImageUpload.stories.js
  src/containers/CommunityModal/CommunityModal.style.ts
  src/containers/CommunityModal/CommunityModal.tsx
  src/containers/CommunityModal/CommunityModalImageUpload/CommunityModalImageUpload.stories.js
  src/containers/CommunityModal/CommunityModalImageUpload/CommunityModalImageUpload.tsx
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButton/CommunityPostCreateButton.style.ts
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButton/CommunityPostCreateButton.tsx
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButtonSection.tsx
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.style.ts
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.tsx
  src/containers/CommunityPostListSection/CommunityPost/CommunityPostMenuIconButton.tsx
  src/containers/CommunityPostListSection/CommunityPostListSection.style.ts
  src/containers/CommunityPostListSection/CommunityPostListSection.tsx
  src/containers/CommunityPostListSection/CommunityPostTypographyButton/CommunityPostTypographyButton.style.ts
  src/containers/CommunityPostListSection/CommunityPostTypographyButton/CommunityPostTypographyButton.tsx
  src/interfaces/community.d.ts
  src/pages/Community/index.tsx
  src/pages/Community/style.ts
  src/router/index.tsx
Labels: 프론트, 페이지

#54 Feature/스터디-생성-수정-validation
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate&Edit/StudyMultiLineInput.tsx
  src/components/StudyCreate/StudyCreateMbtiSelect/StudyCreateMbtiSelect.tsx
  src/constants/selectOptions.ts
  src/containers/StudyCreateForm/StudyCreateForm.tsx
  src/containers/StudyCreateForm/style.ts
  src/containers/StudyEdit/StudyEditForm.tsx
  src/containers/StudyEdit/style.ts
Labels: 리뷰 요청, 프론트, 컨테이너, 기능 구현

#59 Feature/리액트-라우터-버전-변경
  package-lock.json
  package.json
  src/App.tsx
  src/containers/NavigationHeader/NavigationHeader.tsx
  src/containers/index.ts
  src/layout/Layout.tsx
  src/layout/style.ts
  src/pages/SignUp/style.ts
  src/router/index.tsx
Labels: 리뷰 요청, 페이지, 리팩터링, 수정

#60 Feature/api 요청 함수 선구현 및 적용
  public/mock/studyDetailMockData.json
  public/mock/studyDetailQustionMockData.json
  public/mock/studyManageMockData.json
  src/apis/axiosInstance.ts
  src/apis/fetchStudyDetails.ts
  src/apis/studyDetail.ts
  src/components/DefaultAlert/DefaultAlert.stories.js
  src/components/DefaultAlert/DefaultAlert.tsx
  src/components/DefaultAlert/style.ts
  src/components/index.ts
  src/constants/nodeEnv.ts
  src/containers/Reply/Reply.stories.js
  src/containers/Reply/Reply.tsx
  src/containers/Reply/ReplyInput.tsx
  src/containers/Reply/style.ts
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/containers/StudyEdit/StudyEditForm.tsx
  src/containers/StudyManage/MemberControl/MemberControl.stories.js
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/interfaces/error.d.ts
  src/interfaces/studyDetail.d.ts
  src/interfaces/studyDetailQuestion.d.ts
  src/interfaces/studyManage.d.ts
  src/pages/StudyDetail/index.tsx
  src/pages/StudyDetail/style.ts
  src/pages/StudyManage/index.tsx
  src/store/rootReducer.ts
  src/store/slices/question.ts
Labels: 리뷰 요청, 프론트, 기능 구현

#61 Feature/프로필-수정-페이지
  public/mock/userProfile.json
  src/components/Select/Select.tsx
  src/components/index.ts
  src/constants/selectOptions.ts
  src/containers/ProfileEdit/EditForm/EditForm.style.ts
  src/containers/ProfileEdit/EditForm/EditForm.tsx
  src/containers/ProfileEdit/EditFormSection/EditFormSection.style.ts
  src/containers/ProfileEdit/EditFormSection/EditFormSection.tsx
  src/containers/index.ts
  src/interfaces/userProfile.d.ts
  src/pages/ProfileEdit/ProfileEdit.tsx
Labels: 리뷰 요청, 페이지

#63 Feature/스터디-생성-페이지-UI
  src/components/MbtiTag/MbtiTag.style.ts
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate&Edit/StudyMultiLineInput.tsx
  src/components/StudyCreate/StudyCreateMbtiSelect/MbtiBox/MbtiBox.stories.js
  src/components/StudyCreate/StudyCreateMbtiSelect/MbtiBox/MbtiBox.tsx
  src/components/StudyCreate/StudyCreateMbtiSelect/MbtiBox/style.ts
  src/components/StudyCreate/StudyCreateMbtiSelect/StudyCreateMbtiSelect.tsx
  src/components/StudyCreate/StudyCreateMbtiSelect/style.ts
  src/components/StudyCreate/StudyCreateRadioGroup/StudyCreateRadioGroup.tsx
  src/components/StudyCreate/StudyCreateRangeDatePicker/StudyCreateRangeDatePicker.tsx
  src/constants/selectOptions.ts
  src/containers/StudyCreateForm/StudyCreateForm.tsx
  src/containers/StudyCreateForm/style.ts
  src/utils/setMbtiColor.ts
Labels: 리뷰 요청, 컴포넌트, 컨테이너, 리팩터링

#62 Feature/스터디 관리 페이지 api 선적용
  public/mock/studyManageMockData.json
  src/apis/studyDetail.ts
  src/apis/studyManage.ts
  src/containers/FlashAlert/FlashAlert.tsx
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/containers/index.ts
  src/interfaces/studyManage.d.ts
  src/layout/Layout.tsx
  src/pages/StudyDetail/index.tsx
  src/pages/StudyDetail/style.ts
  src/pages/StudyManage/index.tsx
  src/pages/StudyManage/style.ts
  src/store/rootReducer.ts
  src/store/slices/flashAlert.ts
Labels: 리뷰 요청, 프론트, 컴포넌트, 페이지, 기능 구현

#65 feat: NotFound-페이지
  src/pages/NotFound/NotFound.tsx
  src/pages/NotFound/style.ts
  src/pages/index.ts
  src/router/index.tsx
Labels: 프론트, 페이지

#68 Feature/로그인-redux-상태-관리
  public/mock/authUser.json
  public/mock/loginUser.json
  src/apis/user.ts
  src/containers/NavigationHeader/NavigationHeader.tsx
  src/store/rootReducer.ts
  src/store/slices/user.ts
Labels: 리뷰 요청, 컨테이너, 기능 구현

#72 Feature/스터디상세 및 관리 멤버확인 관련 로직 적용
  public/mock/studyDetailMockData.json
  public/mock/studyList0.json
  public/mock/studyList1.json
  public/mock/studyList2.json
  src/apis/axiosInstance.ts
  src/apis/studyDetail.ts
  src/apis/studyGroups.ts
  src/apis/studyManage.ts
  src/apis/user.ts
  src/components/StudyCard/StudyCard.stories.js
  src/components/StudyCard/StudyCard.tsx
  src/containers/Home/StudyListSection/StudyListSection.tsx
  src/containers/Reply/Reply.tsx
  src/containers/StudyDetail/MbtiRecommand/MbtiRecommend.tsx
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/interfaces/studyDetail.d.ts
  src/interfaces/studyList.d.ts
  src/pages/StudyDetail/index.tsx
  src/pages/StudyManage/index.tsx
  src/utils/getOptionLabel.ts
Labels: 리뷰 요청, 프론트, 기능 구현, 리팩터링, 급함🔥, 수정

#73 Feature/로그인-API-연동
  src/apis/axiosInstance.ts
  src/apis/user.ts
  src/constants/oauth.ts
  src/containers/NavigationHeader/NavigationHeader.tsx
  src/containers/NavigationHeader/style.ts
  src/layout/Layout.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  src/router/index.tsx
  src/router/path.ts
  src/utils/storage.ts
Labels: 리뷰 요청, 컨테이너, 페이지, 기능 구현, 급함🔥

#74 Feature/스터디-생성-페이지-API-Alert
  src/apis/studyCreate.ts
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate/StudyCreateRangeDatePicker/StudyCreateRangeDatePicker.tsx
  src/containers/StudyCreateForm/StudyCreateForm.tsx
Labels: 리뷰 요청, 프론트, 컨테이너, 기능 구현

#81 Feature/커뮤니티 페이지 댓글 및 api연동
  public/mock/CommunityMockData.json
  public/mock/communityPostCommentMockData.json
  src/apis/community.ts
  src/containers/CommunityModal/CommunityModal.tsx
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButtonSection.tsx
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.style.ts
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.tsx
  src/containers/CommunityPostListSection/CommunityPostComment/CommunityPostComment.tsx
  src/containers/CommunityPostListSection/CommunityPostComment/style.ts
  src/containers/CommunityPostListSection/CommunityPostListSection.tsx
  src/containers/CommunityPostListSection/CommunityPostMenuIconButton/CommunityPostMenuIconButton.tsx
  src/containers/CommunityPostListSection/CommunityPostTypographyButton/CommunityPostTypographyButton.tsx
  src/interfaces/community.d.ts
  src/pages/Community/index.tsx
  src/store/rootReducer.ts
  src/store/slices/comment.ts
  src/store/slices/post.ts
Labels: 기능 구현

#86 Fix/itemCard-경로-수정
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.tsx
  src/containers/CommunityPostListSection/CommunityPostListSection.tsx
Labels: 급함🔥, 수정

#87 FIX/user-state-type-변경
  src/store/slices/user.ts
Labels: 리뷰 요청, 급함🔥, 수정

#80 Feature/스터디-수정-페이지-API-Alert
  src/apis/studyEdit.ts
  src/components/StudyCreate&Edit/StudyFileInput.tsx
  src/components/StudyCreate&Edit/StudyLabelInput.tsx
  src/components/StudyCreate&Edit/StudyMultiLineInput.tsx
  src/components/StudyCreate/StudyCreateRadioGroup/StudyCreateRadioGroup.tsx
  src/components/StudyCreate/StudyCreateRangeDatePicker/StudyCreateRangeDatePicker.tsx
  src/containers/StudyCreateForm/StudyCreateForm.tsx
  src/containers/StudyEdit/StudyEditForm.tsx
  src/containers/StudyEditForm/StudyEditForm.stories.js
  src/containers/StudyEditForm/StudyEditForm.tsx
  src/containers/StudyEditForm/style.ts
  src/containers/index.ts
Labels: 리뷰 요청, 컨테이너, 페이지, 기능 구현

#83 Feature/회원가입-API-연동
  src/apis/user.ts
  src/constants/externalUrl.ts
  src/containers/SignUp/Form/Form.tsx
  src/containers/SignUp/Select/Select.tsx
  src/interfaces/user.d.ts
  src/router/path.ts
  src/utils/queryString.ts
Labels: 리뷰 요청, 컨테이너, 기능 구현, 리팩터링

#90 Feature/Github-OAuth-로그인-추가
  src/containers/NavigationHeader/NavigationHeader.tsx
Labels: 컨테이너, 기능 구현, 리팩터링

#92 Feature/레이아웃-스크롤-초기화
  src/layout/Layout.tsx
Labels: 프론트, 기능 구현

#94 Feature/스터디상세 및 관리 api auth axios 적용
  src/apis/studyDetail.ts
  src/apis/studyManage.ts
  src/components/UserInfo/UserInfo.tsx
  src/containers/Reply/Reply.tsx
  src/containers/Reply/ReplyInput.tsx
  src/containers/StudyDetail/MbtiRecommand/MbtiRecommend.tsx
  src/containers/StudyDetail/StudyQuestion/StudyQuestion.tsx
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/pages/StudyDetail/index.tsx
  src/pages/StudyManage/index.tsx
Labels: 리뷰 요청, 급함🔥

#93 fix: 스터디 생성 인원 수정
  src/constants/selectOptions.ts
Labels: 수정

#99 Fix/navigation-header-avatar-수정
  src/containers/NavigationHeader/NavigationHeader.tsx
Labels: 리뷰 요청, 컨테이너, 수정

#96 Feature/스터디관리 api 최종확인 및 오류 수정
  src/containers/StudyManage/MemberControl/MemberControl.tsx
  src/interfaces/studyManage.d.ts
  src/pages/StudyManage/index.tsx
  src/store/slices/question.ts
Labels: 리뷰 요청, 프론트, 기능 구현, 리팩터링, 급함🔥, 수정

#97 Feature/private-router-설정
  src/router/PrivateRoute.tsx
  src/router/index.tsx
Labels: 리뷰 요청, 페이지, 기능 구현

#101 Feature/프로필-페이지-기능-추가
  src/apis/members.ts
  src/apis/posts.ts
  src/apis/studyGroups.ts
  src/components/ProfileDetail/UserProfile/UserProfile.style.ts
  src/components/ProfileDetail/UserProfile/UserProfile.tsx
  src/components/StudyCard/SkelectonCard/SkeletonCard.tsx
  src/components/StudyCard/StudyCard.style.ts
  src/components/StudyCard/StudyCard.tsx
  src/components/StudyList/StudyList.tsx
  src/containers/Home/StudyCreateButton/StudyCreateButton.style.ts
  src/containers/Home/StudyListFilter/StudyListFilter.tsx
  src/containers/Home/StudyListSection/StudyListSection.tsx
  src/containers/ProfileDetail/ContentSection/ContentSection.tsx
  src/containers/ProfileDetail/InfoSection/InfoSection.tsx
  src/containers/ProfileDetail/PostTab/PostTab.style.ts
  src/containers/ProfileDetail/PostTab/PostTab.tsx
  src/containers/ProfileDetail/RoleFilter/Role.style.ts
  src/containers/ProfileDetail/RoleFilter/RoleFilter.tsx
  src/containers/ProfileDetail/StudyTab/StudyTab.tsx
  src/containers/ProfileEdit/EditForm/EditForm.style.ts
  src/containers/ProfileEdit/EditForm/EditForm.tsx
  src/containers/ProfileEdit/EditFormSection/EditFormSection.style.ts
  src/interfaces/studyList.d.ts
  src/interfaces/userProfile.d.ts
  src/utils/getOptionLabel.ts
Labels: 리뷰 요청, 페이지, 기능 구현

#102 Feature/커뮤니티 댓글 및 무한스크롤(w. Api)
  src/apis/community.ts
  src/components/SkeletonPost/SkeletonPost.tsx
  src/components/SkeletonPost/style.ts
  src/components/index.ts
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButton/CommunityPostCreateButton.style.ts
  src/containers/CommunityPostCreateButtonSection/CommunityPostCreateButton/CommunityPostCreateButton.tsx
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.tsx
  src/containers/CommunityPostListSection/CommunityPostComment/CommunityPostComment.tsx
  src/containers/CommunityPostListSection/CommunityPostListSection.tsx
  src/containers/ProfileDetail/PostTab/PostTab.tsx
  src/hooks/useIntersectionObserver.ts
  src/interfaces/community.d.ts
  src/store/rootReducer.ts
  src/store/slices/comment.ts
Labels: 페이지, 기능 구현

#103 Fix/스터디-생성-수정
  src/apis/studyDetail.ts
  src/apis/studyManage.ts
  src/components/StudyCreate/StudyCreateRangeDatePicker/StudyCreateRangeDatePicker.tsx
  src/containers/StudyCreateForm/StudyCreateForm.tsx
  src/containers/StudyEditForm/StudyEditForm.tsx
  src/pages/StudyDetail/index.tsx
  src/pages/StudyManage/index.tsx
Labels: 리팩터링

#106 Feature/netlify-redirects-파일-추가
  public/_redirects
Labels: 기능 구현, 급함🔥

#108 Feature/스터디-세부-설명-개행-추가
  src/components/StudyDetail/DetailBody/DetailBody.tsx
  src/containers/CommunityPostListSection/CommunityPost/CommunityPost.tsx
Labels: 리뷰 요청, 리팩터링

#109 Feature/파비콘-추가
  public/favicon.ico
  public/index.html
Labels: 리뷰 요청, 페이지, 수정

#110 Fix/스터디-생성-수정-공백제거
  src/containers/StudyCreateForm/StudyCreateForm.tsx
  src/containers/StudyEditForm/StudyEditForm.tsx
Labels: 수정

#111 Feature/토큰-갱신-처리-구현
  src/apis/axiosInstance.ts
  src/hooks/useAxiosAuthInterceptor.ts
  src/layout/Layout.tsx
  src/store/index.ts
Labels: 리뷰 요청, 기능 구현, 리팩터링

#114 Feature/오픈-그래프-적용
  public/index.html
  src/assets/imgs/og-thumbnail.jpg
Labels: 리뷰 요청, 수정
